# Spring Boot Configuration
spring:
  application:
    name: organization-analysis

  # Externalize Configuration to the Config Server
  config:
    import: optional:configserver:http://localhost:8888
