# Eureka Server Configuration
eureka:
  instance:
    hostname: localhost

  client:
    defaultZone: http://localhost:8761/eureka/

# Server Configuration
server:
  port: 8072

# Spring Boot Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/submitted-project
    username: dashboard
    password: pass
    driver-class-name: org.postgresql.Driver

  # Zipkin Configuration
  management:
    tracing:
      sampling:
        probability: 0.3 # 30% of the requests will be traced (MEDIUM SAMPLING)